[theme]
# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#ef9035"

# Background color for your app
backgroundColor = "#fafafa"

# Secondary background color for your app
secondaryBackgroundColor = "#f2f2f0"

# Text color for your app
textColor = "#4a3735"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"

# Font weight for code in the sidebar (new in 1.48)
codeFontWeight = 900 # or "bold", "bolder", "lighter", "100" to "900"

# Radius for widgets and containers
baseRadius = "medium"

# Color for links
linkColor = "#64748b"

# You can uncomment and adjust these as needed for more granular control:
[theme.fontSizes]
h1 = "3rem"
# h2 = "2rem"
# h3 = "1.75rem"
# h4 = "1.5rem"
# h5 = "1.25rem"
# h6 = "1rem"
# body = "1rem"
# code = "0.875rem"

# [theme.lineHeights]
# h1 = "1.2"
# body = "1.5"

# [theme.spacing]
# xs = "0.25rem"
# sm = "0.5rem"
# md = "1rem"
# lg = "1.5rem"
# xl = "2rem"

[deprecation]
showPyplotGlobalUse = false

[server]
enableStaticServing = false

[upload]
file_formats = ["csv", "xlsx"]
