SUPABASE_URL="https://upjesglgrmzhemzhinll.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwamVzZ2xncm16aGVtemhpbmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTk3MjUsImV4cCI6MjA3MTk3NTcyNX0.FbzQywvz3piw95Vq9EDWEUnpPn6EICEF54juYMkzlnY"
